/**
 * ConfluenceSyncManager — manages the full document lifecycle for ai-sdd artifacts.
 *
 * Responsibilities:
 *  - Keeps an in-memory + file-persisted map: task_id → PageRef
 *  - publishDocument(): create if no mapping, update if mapping exists
 *  - publishWorkflowIndex(): creates/updates a single index page listing all task outputs
 *  - Atomic persistence of page mappings to .ai-sdd/sessions/<session>/confluence-mappings.json
 *
 * Designed to be called from run.ts onPostTask hooks.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, renameSync } from "fs";
import { dirname } from "path";
import type { DocumentAdapter } from "../adapters/document-adapter.ts";
import type { PageRef, Result, AdapterError } from "../types.ts";

const SCHEMA_VERSION = "1" as const;

interface ConfluenceMappingFile {
  schema_version: "1";
  space_key: string;
  saved_at: string;
  mappings: Array<{ task_id: string; page_ref: PageRef }>;
}

function atomicWrite(filePath: string, content: string): void {
  const dir = dirname(filePath);
  mkdirSync(dir, { recursive: true });
  const tmp = `${filePath}.tmp`;
  writeFileSync(tmp, content, "utf-8");
  renameSync(tmp, filePath);
}

export class ConfluenceSyncManager {
  private mappings: Map<string, PageRef> = new Map();

  constructor(
    private readonly adapter: DocumentAdapter,
    private readonly spaceKey: string,
    private readonly parentPageTitle: string = "ai-sdd Artifacts",
  ) {}

  /**
   * Publish a document for a task:
   *  - If no mapping exists → createPage → store mapping
   *  - If mapping exists   → updatePage → update mapping
   *
   * Returns the PageRef on success.
   */
  async publishDocument(
    taskId: string,
    title: string,
    contentMd: string,
  ): Promise<Result<PageRef>> {
    const existing = this.mappings.get(taskId);

    if (!existing) {
      // First publish — create a new page.
      const createResult = await this.adapter.createPage(
        this.spaceKey,
        this.parentPageTitle,
        title,
        contentMd,
      );
      if (!createResult.ok) return createResult;
      this.mappings.set(taskId, createResult.value);
      return createResult;
    }

    // Re-run — update existing page.
    const updateResult = await this.adapter.updatePage(existing, contentMd);
    if (!updateResult.ok) return updateResult;
    this.mappings.set(taskId, updateResult.value);
    return updateResult;
  }

  /**
   * Creates or updates a workflow index page that lists all completed tasks
   * with links to their Confluence pages.
   *
   * @param workflowName Used as part of the index page title.
   * @param taskSummaries Array of {taskId, title, status} for the index body.
   */
  async publishWorkflowIndex(
    workflowName: string,
    taskSummaries: Array<{ taskId: string; title: string; status: string }>,
  ): Promise<Result<PageRef>> {
    const indexTitle = `ai-sdd: ${workflowName} — Index`;
    const indexTaskId = `__workflow_index__${workflowName}`;

    const lines = [
      `# ${workflowName} — Artifact Index`,
      "",
      `_Generated by ai-sdd at ${new Date().toISOString()}_`,
      "",
      "| Task | Title | Status | Page |",
      "| --- | --- | --- | --- |",
    ];

    for (const { taskId, title, status } of taskSummaries) {
      const ref = this.mappings.get(taskId);
      const link = ref ? `[View](${ref.url})` : "—";
      lines.push(`| \`${taskId}\` | ${title} | ${status} | ${link} |`);
    }

    return this.publishDocument(indexTaskId, indexTitle, lines.join("\n"));
  }

  /** Returns all current mappings. */
  getMappings(): Array<{ task_id: string; page_ref: PageRef }> {
    return Array.from(this.mappings.entries()).map(([task_id, page_ref]) => ({ task_id, page_ref }));
  }

  /** Get the PageRef for a specific task (or undefined if not yet published). */
  getPageRef(taskId: string): PageRef | undefined {
    return this.mappings.get(taskId);
  }

  /** Load persisted mappings from disk. No-op if file doesn't exist. */
  async loadMappings(filePath: string): Promise<void> {
    if (!existsSync(filePath)) {
      this.mappings = new Map();
      return;
    }

    let raw: string;
    try {
      raw = readFileSync(filePath, "utf-8");
    } catch (e) {
      throw new Error(`Failed to read Confluence mapping file '${filePath}': ${String(e)}`);
    }

    let parsed: ConfluenceMappingFile;
    try {
      parsed = JSON.parse(raw) as ConfluenceMappingFile;
    } catch {
      throw new Error(`Confluence mapping file '${filePath}' is not valid JSON`);
    }

    if (parsed.schema_version !== SCHEMA_VERSION) {
      throw new Error(
        `Confluence mapping file schema version mismatch at '${filePath}': ` +
        `expected '${SCHEMA_VERSION}', got '${parsed.schema_version}'`,
      );
    }

    this.mappings = new Map(parsed.mappings.map(m => [m.task_id, m.page_ref]));
  }

  /** Atomically persist mappings to disk. */
  async saveMappings(filePath: string): Promise<void> {
    const data: ConfluenceMappingFile = {
      schema_version: SCHEMA_VERSION,
      space_key: this.spaceKey,
      saved_at: new Date().toISOString(),
      mappings: Array.from(this.mappings.entries()).map(([task_id, page_ref]) => ({ task_id, page_ref })),
    };
    atomicWrite(filePath, JSON.stringify(data, null, 2));
  }

  /** Return a descriptive error for failed operations. */
  static makeError(message: string, cause?: unknown): AdapterError {
    return {
      code: "UNKNOWN",
      message,
      retryable: false,
      cause,
    };
  }
}
